---
version: "2.0"
services:
  service-1:
    image: endevjake/search-api:v1.0.0
    expose:
      - port: 5001
        as: 5001
        to:
          - global: true
    env:
      - >-
        SUBGRAPH_URL=https://api.studio.thegraph.com/query/103943/ai-agent-index/version/latest
profiles:
  compute:
    service-1:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          - size: 1Gi
  placement:
    dcloud:
      pricing:
        service-1:
          denom: uakt
          amount: 1000
deployment:
  service-1:
    dcloud:
      profile: service-1
      count: 1
